version: '3.8'

services:
  es_microservice:
    container_name: es_service
    build:
      context: .
      dockerfile: es.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
     - postgres
    networks: [ "microservices" ]
    restart: always
    environment:
      - POSTGRES_URL=postgres://postgres:changeme@postgres_container:5432/postgres?sslmode=disable
      - PORT=3000
      - ENV=prod

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./migration:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - microservices
    restart: unless-stopped

networks:
  microservices:
    name: microservices

volumes:
    postgres:
    pgadmin: