ENV: dev

POSTGRES_URL: postgres://postgres:changeme@localhost:5432/postgres?sslmode=disable

server:
  PORT: 3001

RABBITMQ_URL: amqp://guest:guest@localhost:5672/
MQ_CONFIG_FILE: pkg/config/mq_config.json